-- MySQL Script generated by MySQL Workbench
-- Fri Sep 22 17:31:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Loja_Eletronicos_PHP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Loja_Eletronicos_PHP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Loja_Eletronicos_PHP` DEFAULT CHARACTER SET utf8 ;
USE `Loja_Eletronicos_PHP` ;

-- -----------------------------------------------------
-- Table `Loja_Eletronicos_PHP`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Loja_Eletronicos_PHP`.`Vendedor` (
  `idVendedor` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVendedor`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) ,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
